#!/bin/bash

git_core_editor="vim --nofork +1"
commitmsg_specific_opt="-c 'set fenc=utf-8'"

# Get full path
get_fp() {
    echo "$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"
}

commitmsg_fp=$(get_fp "$(git rev-parse --git-dir)/COMMIT_EDITMSG")
tagmsg_fp=$(get_fp "$(git rev-parse --git-dir)/TAG_EDITMSG")

case "$(get_fp "$1")" in
    ${commitmsg_fp} | ${tagmsg_fp} )
        eval ${git_core_editor} ${commitmsg_specific_opt} "$1"
        ;;
    * )
        eval ${git_core_editor} "$@"
        ;;
esac

